### PR TITLE
Travis2

### PR DESCRIPTION
**Pull request by phemmer**
@zabawaba99

### CODE REVIEW

**Comment by zabawaba99** [comment]
I understand that it _can_ be done to have travis change the directory structure and lowercase `CloudCom` but strongly disagree with doing it. It is going to cause issues with using any other `go` project across this organization alongside `goose`. They all reference `CloudCom` instead of `cloudcom`. 

It is also common to see uppercasing in package names throughout github.

**Comment by phemmer** [comment]
> It is going to cause issues with using any other go project across this organization alongside goose.

What?

**Comment by zabawaba99** [comment]
We have three other `go` packages which reference and use `CloudCom`, there is going to be inconsistencies when trying to get any of those packages with this one. What is the big issue with just leaving it as `CloudCom`? There are tools in just about every editor that auto import packages for you.

**Comment by phemmer** [comment]
Ok. closing as the issue appears to be compatibility with case-insensitive filesystems.

**Pull request closed without merging**
