### PR TITLE
remove go tip from travis build matrix. it's slow

### PR DESCRIPTION
**Pull request by phemmer**
I want to remove `1.3` too, but I figure we can all agree on this at least.

### CODE REVIEW

**Comment by Tonkpils** [comment]
I'd be inclined to leave tip as it'd make sure that we are good to move up in versions but 1.3 should probably be removed.

**Comment by phemmer** [comment]
Except `tip` tests go from git. Do we really want to support unreleased go versions?

**Comment by Tonkpils** [comment]
if there's an error with `tip` we have a better chance of fixing it before we upgrade but I guess its not that big of an issue. We can remove it.

**Comment by zabawaba99** [comment]
Why not

``` ymal
go:
   - 1.4

matrix:
  - allow_failures:
    - go:
        - 1.3
        - tip
  - fast_finish: true
```

That way we can test one version down and one up but not have the entire build fail or wait for all of them to finish

**Comment by zabawaba99** [comment]
Also just a note, I'm not sure that is the proper ymal syntax

**Comment by phemmer** [comment]
If that's possible, I think that would be ok. But I would also question that if we allow them to fail, why test them at all?

**Comment by zabawaba99** [comment]
It is possible to set up a failing matrix. 

As far as why test them, we can be aware of when things start failing and make issues to fix them in the future

**Comment by phemmer** [comment]
> As far as why test them, we can be aware of when things start failing and make issues to fix them in the future

This sounds like it should be part of a periodic build job on the master branch. Not part of PR builds. After all, what happens if there are no PRs to trigger the build?
And who really looks at the PR builds when they don't fail?

**Comment by zabawaba99** [comment]
> This sounds like it should be part of a periodic build job on the master branch. Not part of PR builds. After all, what happens if there are no PRs to trigger the build?

If you'd like to setup a job for it, i'd be completely ok with that. Just seems like a lot more effort than just putting it on travis

> And who really looks at the PR builds when they don't fail?

I do, : /

**Pull request merged**
